---
version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --region us-east-1 --template-file UI/listInvoices/samTemplate.yaml --s3-bucket nejllreports-src-530317771161 --output-template-file UI/listInvoices/samTemplateOut.yaml
artifacts:
  type: zip
  files:
    - UI/listInvoices/samTemplateOut.yaml
