---
version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --region us-east-1 --template-file UI/addInvoice/samTemplate.yaml --s3-bucket nejllreports-src-530317771161 --output-template-file UI/addInvoice/samTemplateOut.yaml
artifacts:
  type: zip
  files:
    - UI/addInvoice/samTemplateOut.yaml
