---
version: 0.2
phases:
  install:
    commands:
      - aws cloudformation package --region us-east-1 --template-file samTemplate.yaml --s3-bucket nejllreports-src --output-template --file samTemplateOut.yaml
artifacts:
  type: zip
  files:
    - samTemplateOut.yaml
