AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: adds an invoice
Resources:
  addInvoiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: addInvoice.addInvoiceHandler
      Runtime: python3.6
      CodeUri: ./
      Events:
        addInvoiceAPI:
          Type: Api
          Properties:
            Path: /addInvoice
            Method: GET
  addInvoiceAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: addInvoice-API
  addInvoiceApiGet:
    Type:  AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      Integration:
        Type: AWS
        IntegrationHttpMethod: GET
        RequestParameters:
          environment: integration.request.querystring.environment
          invoice: integration.request.querystring.invoice
        Uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/
