AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: adds an invoice
Globals:
  Function:
    Runtime: python3.6
    Timeout: 30
Resources:
  addInvoiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: listInvoices.addInvoiceHandler
      CodeUri: ./
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::530317771161:policy/ssmPayPal
      Events:
        addInvoiceAPI:
          Type: Api
          Properties:
            Path: /addInvoice
            Method: post
  listInvoiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: listInvoices.listInvoiceHandler
      CodeUri: ./
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::530317771161:policy/ssmPayPal
      Events:
        listInvoiceAPIGet:
          Type: Api
          Properties:
            Path: /listInvoice
            Method: get
        listInvoiceAPIPost:
          Type: Api
          Properties:
            Path: /listInvoice
            Method: post
  addItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: listInvoices.addItemHandler
      CodeUri: ./
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Events:
        addItemAPI:
          Type: Api
          Properties:
            Path: /addItem
            Method: post
