AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: adds an invoice
Resources:
  addInvoiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: listInvoices.addInvoiceHandler
      Runtime: python3.6
      CodeUri: ./
      Events:
        addInvoiceAPI:
          Type: Api
          Properties:
            Path: /addInvoice
            Method: post
  listInvoiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: listInvoices.listInvoiceHandler
      Runtime: python3.6
      CodeUri: ./
      Events:
        listInvoiceAPI:
          Type: Api
          Properties:
            Path: /listInvoice
            Method: get
