#!/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
  
from __future__ import print_function
from apiclient.discovery import build
from google.oauth2 import service_account
from httplib2 import Http
from oauth2client import file, client, tools
import boto3
from boto3.dynamodb.conditions import Key, Attr
import json
import yaml
import requests
import time
import collections
from optparse import OptionParser

def log_error(msg):
  print(msg)

def getPayPalToken(infile,environment):
  with open(infile, 'r') as stream:
    try:
      y = yaml.load(stream)
    except yaml.YAMLError as e:
      log_error(e)
      exit(1)

  if environment == "sandbox":
    url = "https://api.sandbox.paypal.com/v1/oauth2/token"
  elif environment == "production":
    url = "https://api.paypal.com/v1/oauth2/token"

  headers = { 'Accept': 'application/json',
              'Accept-Language': 'en_US'}

  data = "grant_type=client_credentials"

  r = requests.post(url,auth=(y["environment"][environment]['client_id'],y["environment"][environment]['client_secret']),headers=headers,data=data)

  body = r.json()

  return body['access_token']

def getInvoice(environment,paypal,invoice):
  # Set authorization header
  headers = {'Content-Type': 'application/json',
             'Authorization': 'Bearer '+paypal}

  if environment == "sandbox":
    url = "https://api.sandbox.paypal.com/v1/invoicing/invoices/"+invoice
  elif environment == "production":
    url = "https://api.paypal.com/v1/invoicing/invoices/"+invoice

  r = requests.get(url,headers=headers)

  if r.status_code == 200:
    print(r.json())
  else:
    print("Error finding invoice "+invoice+": Status code = "+str(r.status_code))

# Begin main program
parser = OptionParser()
parser.add_option("-e","--environment", dest="environment", help="Paypal Environment -- OPTIONAL defaults to sandbox [ sandbox, production ]")
parser.add_option("-i","--invoice", dest="invoice", help="Paypal Invoice -- REQUIRED")
parser.add_option("-f","--file",dest="credfile", help="Paypal Credential file (YAML) -- OPTIONAL defaults to paypal.yaml")
parser.add_option("-v","--verbose",dest="verbose", help="Verbose")

(options,args) = parser.parse_args()

if options.environment:
  environment = options.environment
else:
  environment = "sandbox"

if options.credfile:
  credfile = options.credfile
else:
  credfile = "paypal.yaml"

if options.invoice:
  invoice = options.invoice
else:
  log_error("Please supply an invoice!")
  exit(1)

if options.verbose:
  verbose=True
else:
  verbose=False

# Clear the google sheet
paypal = getPayPalToken(credfile,environment)

getInvoice(environment,paypal,invoice)
